[mypy]
python_version = 3.11
strict = True
show_error_codes = True
exclude = (?x)(
    ^build/
    | ^dist/
    | ^\.venv/
    | __pycache__/
  )

[mypy-sounddevice]
ignore_missing_imports = True

[mypy-mss]
ignore_missing_imports = True

[mypy-PIL]
ignore_missing_imports = True

[mypy-google.*]
ignore_missing_imports = True

[mypy-PySide6]
ignore_missing_imports = True

[mypy-keyring]
ignore_missing_imports = True
